service:
  discoveryHost: localhost
  name: serv.access
  port: 3001
  tags: ['v1.0.0', 'microservice', 'serv', 'grpc', 'rest']
  healthCheck:
    timeout: 1s
    interval: 10s
    tcp: host.docker.internal:${{ service.port }}
  maxRetry: 5
  retryInterval: 5000

app:
  refreshToken:
    jwt:
      secret: rawr
      expires: 15m

consul:
  host: localhost
  port: 8500

loadbalance:
  ruleCls: RandomRule

config:
  name: valhalla/config/${{ service.name }}

redis:
  host: localhost
  port: 6379
  password: ''

logger:
  level: info
  transports:
    - transport: console
      colorize: true
      datePattern: YYYY-MM-DD h:mm:ss
      label: ${{ service.name }}
