tenant-billing:
  port: 9900
  database:
    name: 'serv-tenants'

app:
  auth:
    jwt:
      secret: dev
      signOptions:
        expiresIn: 4h

database:
  mongodb:
    uri: mongodb://localhost:27017/valhalla

  # eventStore:
  #   poolMax:
  #   poolMin:
  #   streamProtocol: "http"
  #   hostname: "localhost"
  #   httpPort: 2113
  #   httpProtocol: "http"
  #   tcpPassword: "local"
  #   tcpUsername: "local"
  #   tcpPort: 1113
  #   tcpProtocol: tcp

  redis:
    host: 'localhost'
    port: '6379'
    password: ''
