version: "3.9"
services:
  vahalla:
    container_name: vahalla
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    environment:
      - SERVER=http://localhost:3002
    volumes:
      - ./:/app/
        # Just specify a path and let the Engine create a volume
      - /app/node_modules/
    restart: on-failure

networks:
  turbo-network:
    driver: bridge
