query getOrgMembership {
  organizationMembership {
    profileImageUrl
    status
    role
  }
}

query getOrganizationsMembershipList {
  organizations {
    id
    name
    slug
    name
    logoUrl
  }
}
