database:
  # eventStore:
  #   poolMax:
  #   poolMin:
  #   streamProtocol: "http"
  #   hostname: "localhost"
  #   httpPort: 2113
  #   httpProtocol: "http"
  #   tcpPassword: "local"
  #   tcpUsername: "local"
  #   tcpPort: 1113
  #   tcpProtocol: tcp
