mutation register($input: AccountRegisterInput!) {
  registerAccount(input: $input) {
    accessToken {
      value
      expiresAt
    }
  }
}

mutation logout {
  logout
}

mutation loginWithVerification($input: LoginWithVerificationInput!) {
  loginWithVerification(input: $input) {
    accessToken {
      value
      expiresAt
    }
  }
}

mutation addEmail($email: EmailAddress!) {
  addEmailToAccount(email: $email)
}

mutation removeEmail($emailId: ObjectID!) {
  removeEmailFromAccount(emailId: $emailId)
}

mutation addPhone($phone: PhoneNumber!) {
  addPhoneToAccount(phone: $phone)
}

mutation removePhone($phoneId: ObjectID!) {
  removePhoneFromAccount(phoneId: $phoneId)
}

query getAccount {
  account {
    firstName
    lastName
    displayName
  }
}
