query getComponent($componentId: String!) {
  component(id: $componentId) {
    id
    name
    status
    updatedBy
    thumbnailUrl
    updatedAt
  }
}

query getComponentList {
  componentList {
    id
    name
    thumbnailUrl
  }
}

mutation createComponent($input: CreateComponentInput!) {
  createComponent(input: $input) {
    id
  }
}

mutation updateComponent($componentId: String!, $input: UpdateComponentInput!) {
  updateComponent(id: $componentId, input: $input)
}

mutation archiveComponent($componentId: String!) {
  archiveComponent(id: $componentId)
}

mutation deleteComponent($componentId: String!) {
  deleteComponent(id: $componentId)
}
