fragment Directional on DirectionalSchema {
  top
  bottom
  left
  right
}

fragment Style on StyleSchema {
  margin {
    ...Directional
  }
  padding {
    ...Directional
  }
  borderRadius {
    ...Directional
  }
}

query getFlatElementList($siteId: String!, $pageId: String!) {
  flatElementList(filter: { pageId: $pageId, siteId: $siteId }) {
    __typename
    ... on BoxElementSchema {
      id
      isRoot
      htmlType
      style {
        ...Style
      }
    }
    ... on TextElementSchema {
      text
      id
      style {
        ...Style
      }
    }
  }
}

mutation createBox(
  $ctx: PageContextInput!
  $style: StyleInput
  $parent: String!
  $htmlType: HTMLType
) {
  createBox(
    input: { parent: $parent, ctx: $ctx, style: $style, htmlType: $htmlType }
  )
}

mutation updateBox(
  $elementId: String!
  $ctx: PageContextInput!
  $style: StyleInput
  $parent: String!
) {
  updateBox(
    input: { elementId: $elementId, parent: $parent, ctx: $ctx, style: $style }
  )
}

mutation createText(
  $ctx: PageContextInput!
  $style: StyleInput
  $parent: String!
  $text: String!
) {
  createText(input: { text: $text, parent: $parent, ctx: $ctx, style: $style })
}

mutation updateText(
  $ctx: PageContextInput!
  $style: StyleInput
  $text: String
  $parent: String!
  $elementId: String!
) {
  updateText(
    input: {
      text: $text
      style: $style
      ctx: $ctx
      elementId: $elementId
      parent: $parent
    }
  )
}
