query getOrgMembership {
  organizationMembershipProfile {
    profileImageUrl
    status
    role
  }
}

query getOrgsMembershipList {
  organizationsByMemberships {
    id
    name
    slug
    name
    logoUrl
  }
}
