query getCurrentOrganization {
  organizationByMembership {
    name
    logoUrl
    plan
    slug
  }
}

query findOrganizationBySlug($slug: String!) {
  organizationBySlug(slug: $slug) {
    id
    name
  }
}

mutation createOrganization($input: CreateOrganizationInput!) {
  createOrganization(input: $input) {
    id
  }
}

mutation archiveOrganization($orgId: ObjectID!) {
  archiveOrganization(orgId: $orgId)
}

mutation restoreOrganization($orgId: ObjectID!) {
  restoreOrganization(orgId: $orgId)
}
