query getCurrentOrganization {
  organization {
    name
    logoUrl
    plan
    slug
  }
}

query findOrganizationBySlug($slug: String!) {
  organizationBySlug(slug: $slug) {
    id
    name
  }
}

mutation createOrganization($name: String!, $plan: OrganizationPlan!) {
  createOrganization(input: { name: $name, plan: $plan }) {
    id
    slug
    name
    plan
  }
}

mutation archiveOrganization($orgId: String!) {
  archiveOrganization(orgId: $orgId)
}

mutation restoreOrganization($orgId: String!) {
  restoreOrganization(orgId: $orgId)
}
