query getPageSection($sectionId: String!) {
  section(sectionId: $sectionId) {
    id
    format {
      rowsCount
      rowGap
      columnGap
    }
  }
}

query getPageSectionList($pageId: String!) {
  sectionList(pageId: $pageId) {
    id
    createdAt
    updatedAt
    updatedBy
    format {
      rowsCount
      rowGap
      columnGap
      updatedBy
    }
  }
}

mutation createPageSection($pageId: String!, $input: CreateSectionInput!) {
  createSection(pageId: $pageId, input: $input) {
    id
  }
}

mutation deletePageSection($pageId: String!, $sectionId: String!) {
  deleteSection(pageId: $pageId, sectionId: $sectionId) {
    id
  }
}

mutation updatePageSectionIndex(
  $pageId: String!
  $sectionId: String!
  $index: Float!
) {
  updateSectionHead(pageId: $pageId, sectionId: $sectionId, index: $index) {
    id
  }
}

mutation updatePageSectionFormat(
  $pageId: String!
  $sectionId: String!
  $input: UpdateSectionFormatInput!
) {
  updateSectionFormat(pageId: $pageId, sectionId: $sectionId, input: $input) {
    id
  }
}

mutation clonePageSection($pageId: String!, $sectionId: String!) {
  cloneSection(pageId: $pageId, sectionId: $sectionId) {
    id
  }
}
