query getPageList($siteId: String!) {
  pageList(siteId: $siteId) {
    id
    title
    status
  }
}

query getPage($siteId: String!, $pageId: String!) {
  page(siteId: $siteId, id: $pageId) {
    id
    title
    status
    isLoneTitle
    description
    createdAt
    updatedAt
    createdBy
    updatedBy
  }
}

mutation createPage($siteId: String!, $prop: CreatePageInput!) {
  createPage(siteId: $siteId, input: $prop) {
    id
    status
  }
}

mutation updatePage(
  $siteId: String!
  $pageId: String!
  $input: UpdatePageInput!
) {
  updatePage(siteId: $siteId, id: $pageId, input: $input) {
    status
  }
}

mutation deletePage($siteId: String!, $pageId: String!) {
  deletePage(siteId: $siteId, id: $pageId) {
    status
  }
}

mutation getFirstPage($siteId: String!) {
  getOrCreateFirstPage(siteId: $siteId) {
    id
  }
}
