fragment Position on ElementArea {
  x
  y
  width
  height
  isVisible
}

query getElementsByGroup($groupId: ObjectID!) {
  elementsByGroup(groupId: $groupId) {
    __typename

    ... on ElementText {
      id
      json
      html
      type
      group

      createdAt
      updatedAt
      createdBy
      updatedBy

      desktop {
        ...Position
      }
      mobile {
        ...Position
      }
      tablet {
        ...Position
      }
    }
  }
}

mutation addTextElement($groupId: ObjectID!, $input: AddTextElementInput!) {
  addTextElement(groupId: $groupId, input: $input) {
    id
  }
}

mutation updateTextElement(
  $elementId: ObjectID!
  $input: UpdateTextElementInput!
) {
  updateTextElement(elementId: $elementId, input: $input) {
    id
  }
}

mutation deleteManyElements($elementIds: [ObjectID!]!) {
  deleteManyElements(elementIds: $elementIds) {
    ... on ElementText {
      id
    }
  }
}
