query getPageList($siteId: String!) {
  pageList(siteId: $siteId) {
    id
    title
    status
  }
}

query getPage($pageId: String!) {
  page(id: $pageId) {
    id
    title
    status
    isLoneTitle
    description
    createdAt
    updatedAt
    createdBy
    updatedBy
  }
}

mutation createPage($siteId: String!, $prop: CreatePageInput!) {
  createPage(siteId: $siteId, input: $prop) {
    id
    status
  }
}

mutation updatePage($pageId: String!, $input: UpdatePageInput!) {
  updatePage(id: $pageId, input: $input) {
    status
  }
}

mutation deletePage($pageId: String!) {
  deletePage(id: $pageId) {
    status
  }
}
