query getSites {
  siteByOwner {
    id
    name
    status
  }
}

query getSite($siteId: ObjectID!) {
  site(siteId: $siteId) {
    id
    name
    updatedAt
  }
}

mutation createSite($input: CreateSiteInput!) {
  createSite(input: $input) {
    id
  }
}

mutation updateSite($siteId: ObjectID!, $input: UpdateSiteInput!) {
  updateSite(siteId: $siteId, input: $input) {
    id
    status
  }
}
