query getSites {
  siteList {
    id
    name
    status
  }
}

query getSite($siteId: String!) {
  site(id: $siteId) {
    id
    name
    updatedAt
  }
}

mutation createSite($name: String!) {
  createSite(input: { name: $name }) {
    id
  }
}

mutation updateSite($siteId: String!, $name: String!) {
  updateSite(input: { name: $name }, id: $siteId) {
    id
    status
  }
}
