mutation sendVerification(
  $channel: VerificationChannel!
  $destination: String!
) {
  sendVerificationCode(channel: $channel, destination: $destination)
}

query validateVerificationCode(
  $verificationId: String!
  $verificationCode: String!
) {
  validateVerificationCode(
    verificationId: $verificationId
    verificationCode: $verificationCode
  )
}
