service:
  discoveryHost: localhost
  name: serv.identity
  port: 3005
  tags: ['v1.0.0', 'microservice', 'serv', 'grpc', 'rest', 'graphql']
  maxRetry: 5
  retryInterval: 5000
  healthCheck:
    timeout: 1s
    interval: 10s
    tcp: host.docker.internal:${{ service.port }}

app:
  passwordExpires: 1h
  passwordHashRound: 10
  refreshToken:
    expiresIn: 1y
  accessToken:
    jwt:
      secret: rawr
      signOptions:
        expiresIn: 8h

mongodb:
  uri: mongodb://localhost:27017/valhalla

grpc:
  port: 3015

consul:
  host: localhost
  port: 8500

loadbalance:
  ruleCls: RandomRule

config:
  name: valhalla/config/${{ service.name }}

redis:
  host: localhost
  port: 6379
  password: ''

logger:
  level: info
  transports:
    - transport: console
      colorize: true
      datePattern: YYYY-MM-DD h:mm:ss
      label: ${{ service.name }}
