service:
  discoveryHost: localhost
  name: serv.orgs
  port: 3003
  tags: ['v1.0.0', 'microservice', 'serv', 'grpc', 'rest', 'graphql']
  healthCheck:
    timeout: 1s
    interval: 10s
    tcp: host.docker.internal:${{ service.port }}
  maxRetry: 5
  retryInterval: 5000

consul:
  host: localhost
  port: 8500

mongodb:
  uri: mongodb://localhost:27017/valhalla

loadbalance:
  ruleCls: RandomRule

config:
  name: valhalla/config/${{ service.name }}

redis:
  host: localhost
  port: 6379
  password: ''

logger:
  level: info
  transports:
    - transport: console
      colorize: true
      datePattern: YYYY-MM-DD h:mm:ss
      label: ${{ service.name }}
